### ISSUE TITLE
jwt_sec_file: Reload file for rotating public key support

### ISSUE THREAD

**Issue by davidgraeff** [wiomoc/mosquitto-jwt-auth#1]
First of all, thanks for this crate!

For a long running mosquitto instance, it might be beneficial if the jwt public key file can be re-loaded instead of only reading it in once at start. This is because a lot of jwt servers have rotating public keys.

I thought about a spawned thread somewhere around here:

https://github.com/wiomoc/mosquitto-jwt-auth/blob/24aad46d4bfb5a3cb2268097ad18dbed24a85ef0/src/lib.rs#L38

With either another option like "auth_opt_jwt_sec_reload_sec 3600" or a file watch mechanism.

The secret would no longer be in `secret: Vec<u8>` but in `secret: ArcSwap<Vec<u8>>` (see arc_swap crate). ArcSwap basically allows thread safe pointer swaps and exterior mutability. 

WDYT?

**Comment by wiomoc** [comment]
I havn't tried that, but it seams like Mosquitto supports configuration reloading with sth like `sudo service mosquitto reload`.

This should, according to the [docs](https://mosquitto.org/api/files2/mosquitto_plugin-h.html#mosquitto_auth_security_init), reload the auth plugin too.
https://stackoverflow.com/questions/39126688/mosquitto-reload-config-file

**Comment by davidgraeff** [comment]
That works of course. It is a bit more involved if mosquitto is running via a software container engine. 

Rotating keys require a few more things as well, because an old and a new key may overlap. The key to be used is selected via the JWT key_id header.

There is a standard format for those keys called JWK. And a set of those keys (for the rotating key scenario) is called JWKS. Usually those are to be found at service specific urls within `.well-known/jwks.json` like in `https://YOUR_DOMAIN/.well-known/jwks.json`, but to keep dependencies low a file support is absolutely sufficient.

Would you accept a set of PRs to add support for this?

A first PR would add input support for JWK. The file extension decides how to read the input file (.der, .pem, .jwk).

A subsequent 2nd PR would then add support for multiple keys, via JWKS. Instead of a single `secret: Vec<u8>` there would be a `BTreeMap<String, Vec<u8>`.

And a third PR would introduce a thread and ArcSwap as outlined above to keep the jwks up to date.

**Comment by wiomoc** [comment]
> Would you accept a set of PRs to add support for this?

Sure, thank you in advance.

We should keep the 'plain' key strategy, so consider adding an Enum like this:

   ```rust 
enum KeyMaterial {
    JWKS(BTreeMap<String, Vec<u8>),
    Plain{secret: Vec<u8>}
}
```

**Comment by wiomoc** [comment]
In this run we even could change the JWT implementation to 'biscuit' which supports handling of both JWTs and JWKs. I've alread opened a PR for direct JWK based JWT verification https://github.com/lawliet89/biscuit/pull/124

**Comment by davidgraeff** [comment]
Yeah I would have proposed a change for using biscuit. I'm using it myself and I think it is better maintained and I knew about their JWK/JWKs support. Nice addition of yours though.

**Comment by davidgraeff** [comment]
Thanks a lot
