### ISSUE TITLE
Not able to publish after configuring jwt token

### ISSUE THREAD

**Issue by bhavyashah98** [wiomoc/mosquitto-jwt-auth#15]
mosquitto_pub -h localhost -t test -m "hello world" -u "root" -P "eyJhbGciOiJIUzI1NiJ9.eyJVc2VybmFtZSI6InJvb3QiLCJleHAiOjE2NTU5MDYwODcsImlhdCI6MTY1NTY0Njg4N30.LVRjr3uW_VZv_hbBQUijGELVgKkEZSGdSOBOR0L2EPo" -p 8083

When I publish, I am getting
`Error: The connection was lost.` 
I am able to subscribe to it with JWT Token.

Do I need to configure ACL for this as I currently have no ACL file?

**Comment by wiomoc** [comment]
The JWT misses a `sub` claim and the ACL.

See: https://github.com/wiomoc/mosquitto-jwt-auth#custom-claims
