### ISSUE TITLE
recommended way to install mosquitto-jwt-auth in docker

### ISSUE THREAD

**Issue by stefanfoulis** [wiomoc/mosquitto-jwt-auth#2]
I am new to mosquitto and rust and am probably just missing some very obvious information.
I couldn't figure out yet how to install this plugin.
I am currently using the official [docker image
](https://hub.docker.com/_/eclipse-mosquitto).

Ideally I'd like to use the official image and just add a few layers to it to install this plugin.

I've seen other plugins install themselves using `git clone` and `make`, however this plugin does not have a `Makefile`.
Here I see there seems to be a cargo package. However if I do `cargo install mosquitto-jwt-auth` I get this error:
```
Step 6/11 : RUN cargo install mosquitto-jwt-auth
 ---> Running in f96144d4d563
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading mosquitto-jwt-auth v0.2.0
  Installing mosquitto-jwt-auth v0.2.0
error: specified package has no binaries
ERROR: Service 'mqtt' failed to build: The command '/bin/sh -c cargo install mosquitto-jwt-auth' returned a non-zero code: 101
```

**Comment by wiomoc** [comment]
I've added in 4ab4b86 some documentation about the build process and as well a [prebuild release](https://github.com/wiomoc/mosquitto-jwt-auth/releases/download/0.2.0/libmosquitto_jwt_auth.so) 

Also I had success with this Dockerfile:
```Dockerfile
FROM eclipse-mosquitto
RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.11/main/' > /etc/apk/repositories && \
    echo 'http://dl-cdn.alpinelinux.org/alpine/v3.11/community/' >> /etc/apk/repositories && \
    apk update && \
    apk add libgcc libc6-compat rust cargo && \
    wget https://github.com/wiomoc/mosquitto-jwt-auth/archive/master.zip && \
    unzip master.zip && \
    cd mosquitto-jwt-auth-master && \
    cargo build --release && \
    apk del cargo rust && \
    cd .. && \
    mv mosquitto-jwt-auth-master/target/release/libmosquitto_jwt_auth.so /mosquitto/jwt_auth.so && \
    rm mosquitto-jwt-auth-master -rf
RUN echo  "auth_plugin /mosquitto/jwt_auth.so" >> /mosquitto/config/mosquitto.conf
```

**Comment by stefanfoulis** [comment]
Awesome, thanks @wiomoc 👍

**Comment by moo-im-a-cow** [comment]
sorry for commenting on an old / closed issue, but i managed to get a much smaller image by using a multistage dockerfile

original eclipse-mosquitto image: 5 mb
dockerfile above: 84 mb
my dockerfile: 11mb


only the 2 layers under the 2nd "FROM" are part of the image, everything else is cached on your machine until docker decides to delete it or you run docker purge.


```Dockerfile
FROM eclipse-mosquitto as builder
RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.11/main/' > /etc/apk/repositories && \
    echo 'http://dl-cdn.alpinelinux.org/alpine/v3.11/community/' >> /etc/apk/repositories && \
    apk add libgcc libc6-compat rust cargo git && \
    git clone https://github.com/wiomoc/mosquitto-jwt-auth.git && \
    cd mosquitto-jwt-auth && \
    cargo build --release

FROM eclipse-mosquitto
COPY --from=builder /mosquitto-jwt-auth/target/release/libmosquitto_jwt_auth.so /mosquitto/jwt_auth.so
RUN apk add --no-cache libgcc libc6-compat && \
    echo  "auth_plugin /mosquitto/jwt_auth.so" >> /mosquitto/config/mosquitto.conf
```
