### ISSUE TITLE
Configuring mosquitto.conf

### ISSUE THREAD

**Issue by fromnowhereuser** [wiomoc/mosquitto-jwt-auth#4]
Sorry for posting here, i have few questions...

1) i configured my mosquitto.conf like this:

auth_plugin /home/user/mosquitoplugin/mosquitto-jwt-auth-master/target/release/libmosquitto_jwt_auth.so

auth_opt_jwt_alg HS256
auth_opt_jwt_sec_file /home/user/secret.txt
auth_opt_jwt_validate_exp false
auth_opt_jwt_validate_sub_match_username false

in the secret.txt i put a simple string. 

Is this ok ?

Also, what are those options stand for ?
auth_opt_jwt_sec_env
auth_opt_jwt_sec_base64

i thought only the secret specified here auth_opt_jwt_sec_file matters. Can you give me some advise ? i'm a bit lost :)

**Comment by wiomoc** [comment]
First of all, if `home/user/secret.txt` contains your key you're already good to go.👍
The other two options are only used if you want to provide the key in a different way:
* `auth_opt_jwt_sec_env` you provide the key base64 encoded in an environment variable, the value of these setting is the name of the enviroment variable
* `auth_opt_jwt_sec_base64` you provide the key right away in the *conf* file base64 encoded

https://github.com/wiomoc/mosquitto-jwt-auth/blob/1be4f3e2b85f7e2d25502c8323daac793935bfbe/src/lib.rs#L30-L49
