### ISSUE TITLE
ACL doesn't allow subscriptions to topics with wildcards, even if permissions would allow it

### ISSUE THREAD

**Issue by jeffhos** [wiomoc/mosquitto-jwt-auth#5]
Hi!  I was delighted to find this plugin, which seems like exactly what I need for a project I'm working on. 
 However, in the particular way I'm using it, it's exhibiting some behavior that's unexpected (to me at least)... not sure if it's a bug, or if I'm misunderstanding how this behavior is supposed to work.

So when the user authenticates against my web app, it looks up which "room" the user is supposed to have access to, and issues them a JWT that gives them permission to publish and subscribe to any topic under that room ID, using a multi-level wildcard:

```JSON
{
  "iat": 1588141196,
  "exp": 1588227596,
  "sub": "d2925b0f-23ce-42ee-9a0e-f3779d3970bd",
  "publ": [
    "1/#"
  ],
  "subs": [
    "1/#"
  ]
}
```

When the client connects to Mosquitto, they present the token, and are successfully authenticated.  Then they attempt to subscribe to `1/#`, but the subscription doesn't seem to work.

It seems that `mostquitto-jwt-auth` is rejecting the subscription to `1/#`, even though the user is presenting a token that gives them `subs` permission to `1/#`.

Just to double-check that this is what the plugin is doing, and not a configuration error on my party, I tweaked one of the unit tests to test my use case:

```rust
    #[test]
    fn test_acl_check() {
        let mut instance = MosquittoJWTAuthPluginInstance::new();
        instance.config = Some(MosquittoJWTAuthPluginConfig {
            validation: Validation::default(),
            validate_sub_match_username: true,
            secret: Vec::new(),
        });

        let client_id0 = 33 as ClientID;

        instance.client_permissions.insert(
            client_id0,
            Permissions {
                r#pub: Vec::new(),
                sub: vec![
                    topic_utils::parse_topic_path("1/#", true).unwrap(),
                ],
            },
        );

        let result = instance.acl_check(client_id0, AclType::Subscribe, "1/#");
        assert_eq!(result, Ok(()));
    }
```

This test fails, returning `Err(())` instead of `Ok(())`.

I should also note that this behavior seems to differ from the normal ACL behavior for Mosquitto.  If I create an `acl_file` like this:

```
user testuser
topic readwrite 1/#
```

... the user seems to be able to subscribe to all topics under `1/` using `1/#`

**Comment by wiomoc** [comment]
Thank you a lot for the report!
I've now fixed the wildcard handing for subscription.

**Comment by jeffhos** [comment]
Wow, thanks for the quick fix!
